
name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        id: docker_build
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t "${{ secrets.DOCKERHUB_USERNAME }}/whatzapp:1.0" -f Dockerfile .
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/whatzapp:1.0"

      - name: Run Docker container
        run: docker run -d -p 3200:3000"${{ secrets.DOCKERHUB_USERNAME }}/whatzapp:1.0"
